-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.approval_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reference_type character varying NOT NULL,
  reference_id uuid NOT NULL,
  workflow_step integer NOT NULL,
  approver_role character varying NOT NULL,
  approver_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  comments text,
  approved_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT approval_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT approval_workflows_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_trail (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['create'::character varying, 'update'::character varying, 'delete'::character varying]::text[])),
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  ip_address inet,
  user_agent text,
  CONSTRAINT audit_trail_pkey PRIMARY KEY (id),
  CONSTRAINT audit_trail_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.business_entities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  legal_name character varying,
  gst_number character varying,
  tax_id character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  phone character varying,
  email character varying,
  logo_url character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT business_entities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chart_of_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_code character varying NOT NULL UNIQUE,
  account_name character varying NOT NULL,
  account_type character varying NOT NULL CHECK (account_type::text = ANY (ARRAY['asset'::character varying, 'liability'::character varying, 'equity'::character varying, 'revenue'::character varying, 'expense'::character varying]::text[])),
  parent_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT chart_of_accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.compliance_checklist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  compliance_type character varying NOT NULL,
  description text NOT NULL,
  is_required boolean DEFAULT true,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'not_applicable'::character varying, 'expired'::character varying, 'overdue'::character varying]::text[])),
  due_date date,
  completed_date date,
  document_reference character varying,
  issuing_authority character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  assigned_to uuid,
  notes text,
  CONSTRAINT compliance_checklist_pkey PRIMARY KEY (id),
  CONSTRAINT fk_compliance_checklist_shipment FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  contact_person character varying,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  credit_limit numeric DEFAULT 0,
  payment_terms integer DEFAULT 30,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fax character varying,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.customs_declarations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  declaration_number character varying NOT NULL UNIQUE,
  shipment_id uuid NOT NULL,
  declaration_type character varying NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'submitted'::character varying, 'under_review'::character varying, 'cleared'::character varying, 'held'::character varying, 'rejected'::character varying]::text[])),
  customs_office character varying,
  declaration_date date,
  clearance_date date,
  customs_officer character varying,
  declared_value numeric,
  currency character varying DEFAULT 'USD'::character varying,
  duty_amount numeric,
  tax_amount numeric,
  total_charges numeric,
  document_reference character varying,
  certificate_number character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  notes text,
  CONSTRAINT customs_declarations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_customs_shipment FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.delivery_challans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challan_number character varying NOT NULL UNIQUE,
  purchase_order_id uuid NOT NULL,
  challan_date date NOT NULL,
  delivery_date date,
  delivery_address text,
  contact_person character varying,
  phone character varying,
  notes text,
  status character varying DEFAULT 'generated'::character varying CHECK (status::text = ANY (ARRAY['generated'::character varying::text, 'dispatched'::character varying::text, 'in_transit'::character varying::text, 'delivered'::character varying::text, 'cancelled'::character varying::text])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT delivery_challans_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_challans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT delivery_challans_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.delivery_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid NOT NULL,
  tracking_number character varying,
  carrier_name character varying,
  shipped_date timestamp without time zone,
  delivered_date timestamp without time zone,
  delivery_address text,
  delivery_notes text,
  delivery_status character varying DEFAULT 'pending'::character varying CHECK (delivery_status::text = ANY (ARRAY['pending'::character varying::text, 'picked_up'::character varying::text, 'in_transit'::character varying::text, 'out_for_delivery'::character varying::text, 'delivered'::character varying::text, 'failed'::character varying::text, 'returned'::character varying::text])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT delivery_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_tracking_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id)
);
CREATE TABLE public.document_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reference_type character varying NOT NULL,
  reference_id uuid NOT NULL,
  file_name character varying NOT NULL,
  file_path character varying NOT NULL,
  file_size integer,
  mime_type character varying,
  uploaded_by uuid,
  uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  document_type character varying,
  linked_reference_type character varying,
  linked_reference_number character varying,
  linked_reference_id uuid,
  customer_id uuid,
  vendor_id uuid,
  business_entity_id uuid,
  compliance_status character varying DEFAULT 'pending'::character varying CHECK (compliance_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'under_review'::character varying]::text[])),
  compliance_notes text,
  ocr_status character varying DEFAULT 'pending'::character varying CHECK (ocr_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  document_date date,
  expiry_date date,
  issuing_authority character varying,
  country_of_origin character varying,
  notes text,
  CONSTRAINT document_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT document_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT document_attachments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT document_attachments_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT document_attachments_business_entity_id_fkey FOREIGN KEY (business_entity_id) REFERENCES public.business_entities(id)
);
CREATE TABLE public.hs_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hs_code character varying NOT NULL UNIQUE,
  description text NOT NULL,
  duty_rate numeric,
  tax_rate numeric,
  category character varying,
  country_code character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT hs_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  product_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  discount_percent numeric DEFAULT 0,
  tax_percent numeric DEFAULT 0,
  line_total numeric NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number character varying NOT NULL UNIQUE,
  sales_order_id uuid,
  customer_id uuid NOT NULL,
  business_entity_id uuid,
  invoice_date date NOT NULL,
  due_date date NOT NULL,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'paid'::character varying, 'overdue'::character varying, 'cancelled'::character varying]::text[])),
  subtotal numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  paid_amount numeric DEFAULT 0,
  fbr_sync_status character varying DEFAULT 'pending'::character varying CHECK (fbr_sync_status::text = ANY (ARRAY['pending'::character varying, 'synced'::character varying, 'failed'::character varying]::text[])),
  fbr_sync_date timestamp without time zone,
  fbr_reference character varying,
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  notes text,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT invoices_business_entity_id_fkey FOREIGN KEY (business_entity_id) REFERENCES public.business_entities(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.landed_costs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  goods_value numeric NOT NULL,
  freight_cost numeric,
  insurance_cost numeric,
  customs_duty numeric,
  import_tax numeric,
  vat_amount numeric,
  handling_charges numeric,
  storage_charges numeric,
  documentation_fees numeric,
  broker_fees numeric,
  other_charges numeric,
  total_landed_cost numeric,
  currency character varying DEFAULT 'USD'::character varying,
  exchange_rate numeric,
  rate_date date,
  base_currency character varying,
  calculated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  calculated_by uuid,
  is_final boolean DEFAULT false,
  notes text,
  CONSTRAINT landed_costs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_landed_costs_shipment FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.ledger_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_number character varying NOT NULL UNIQUE,
  entry_date date NOT NULL,
  reference_type character varying,
  reference_id uuid,
  reference_number character varying,
  description text NOT NULL,
  total_debit numeric DEFAULT 0,
  total_credit numeric DEFAULT 0,
  status character varying DEFAULT 'posted'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'posted'::character varying, 'reversed'::character varying]::text[])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ledger_entries_pkey PRIMARY KEY (id),
  CONSTRAINT ledger_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.ledger_entry_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ledger_entry_id uuid NOT NULL,
  account_id uuid NOT NULL,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  description text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ledger_entry_lines_pkey PRIMARY KEY (id),
  CONSTRAINT ledger_entry_lines_ledger_entry_id_fkey FOREIGN KEY (ledger_entry_id) REFERENCES public.ledger_entries(id),
  CONSTRAINT ledger_entry_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.logistics_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  status character varying NOT NULL,
  location character varying,
  timestamp timestamp without time zone NOT NULL,
  description text,
  carrier_reference character varying,
  estimated_delivery timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  CONSTRAINT logistics_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT fk_logistics_tracking_shipment FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.ocr_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid,
  extracted_text text,
  confidence_score numeric,
  processing_status character varying DEFAULT 'pending'::character varying CHECK (processing_status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  processed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  language character varying DEFAULT 'en'::character varying,
  processing_engine character varying,
  extracted_entities jsonb,
  processed_by uuid,
  CONSTRAINT ocr_results_pkey PRIMARY KEY (id),
  CONSTRAINT ocr_results_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_attachments(id),
  CONSTRAINT ocr_results_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id)
);
CREATE TABLE public.product_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  parent_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_categories_pkey PRIMARY KEY (id),
  CONSTRAINT product_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.product_categories(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sku character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  category_id uuid,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['raw_material'::character varying, 'finished_good'::character varying, 'service'::character varying, 'spare_parts'::character varying]::text[])),
  unit_of_measure character varying NOT NULL,
  current_stock numeric DEFAULT 0,
  reorder_point numeric DEFAULT 0,
  max_stock_level numeric,
  last_purchase_price numeric,
  average_cost numeric,
  selling_price numeric,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'discontinued'::character varying]::text[])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id),
  CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  product_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  discount_percent numeric DEFAULT 0,
  tax_percent numeric DEFAULT 0,
  line_total numeric NOT NULL,
  received_quantity numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  po_number character varying NOT NULL UNIQUE,
  vendor_id uuid NOT NULL,
  business_entity_id uuid,
  quotation_id uuid,
  sales_order_id uuid,
  po_date date NOT NULL,
  expected_delivery_date date,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'pending_approval'::character varying, 'approved'::character varying, 'sent'::character varying, 'received'::character varying, 'closed'::character varying, 'cancelled'::character varying]::text[])),
  subtotal numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  terms_conditions text,
  notes text,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT purchase_orders_business_entity_id_fkey FOREIGN KEY (business_entity_id) REFERENCES public.business_entities(id),
  CONSTRAINT purchase_orders_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id),
  CONSTRAINT purchase_orders_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT purchase_orders_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.quotation_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quotation_id uuid NOT NULL,
  product_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  discount_percent numeric DEFAULT 0,
  tax_percent numeric DEFAULT 0,
  line_total numeric NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  selected_for_customer boolean DEFAULT false,
  vendor_item_id uuid,
  client_markup_percentage numeric DEFAULT 0,
  client_markup_amount numeric DEFAULT 0,
  customer_price numeric,
  item_notes text,
  category character varying,
  serial_number character varying,
  item_name character varying,
  unit_of_measure character varying,
  gst_percent numeric DEFAULT 0,
  item_type character varying DEFAULT 'inventory'::character varying CHECK (item_type::text = ANY (ARRAY['inventory'::character varying, 'custom'::character varying]::text[])),
  au_field character varying DEFAULT 'No'::character varying CHECK (au_field::text = ANY (ARRAY['Yes'::character varying, 'No'::character varying]::text[])),
  CONSTRAINT quotation_items_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_items_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id),
  CONSTRAINT quotation_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.quotations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quotation_number character varying NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  business_entity_id uuid,
  quotation_date date NOT NULL,
  valid_until date,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'approved'::character varying, 'rejected'::character varying, 'expired'::character varying, 'converted'::character varying]::text[])),
  subtotal numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  terms_conditions text,
  notes text,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  quotation_type character varying DEFAULT 'customer_request'::character varying,
  parent_quotation_id uuid,
  vendor_id uuid,
  workflow_status character varying DEFAULT 'draft'::character varying,
  pdf_generated boolean DEFAULT false,
  pdf_url character varying,
  reference_number character varying,
  CONSTRAINT quotations_pkey PRIMARY KEY (id),
  CONSTRAINT quotations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT quotations_business_entity_id_fkey FOREIGN KEY (business_entity_id) REFERENCES public.business_entities(id),
  CONSTRAINT quotations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT quotations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT quotations_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT quotations_parent_quotation_id_fkey FOREIGN KEY (parent_quotation_id) REFERENCES public.quotations(id)
);
CREATE TABLE public.rate_request_vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rate_request_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'sent'::character varying::text, 'responded'::character varying::text, 'declined'::character varying::text])),
  sent_at timestamp without time zone,
  responded_at timestamp without time zone,
  email_sent boolean DEFAULT false,
  whatsapp_sent boolean DEFAULT false,
  response_data jsonb,
  quoted_price numeric,
  quoted_delivery_time integer,
  vendor_notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT rate_request_vendors_pkey PRIMARY KEY (id),
  CONSTRAINT rate_request_vendors_rate_request_id_fkey FOREIGN KEY (rate_request_id) REFERENCES public.rate_requests(id),
  CONSTRAINT rate_request_vendors_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.rate_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_number character varying NOT NULL UNIQUE,
  category_id uuid NOT NULL,
  quotation_id uuid,
  quotation_item_id uuid,
  request_type character varying DEFAULT 'category'::character varying CHECK (request_type::text = ANY (ARRAY['category'::character varying::text, 'specific_item'::character varying::text])),
  title character varying NOT NULL,
  description text,
  quantity numeric,
  unit_of_measure character varying,
  specifications jsonb,
  deadline date,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'sent'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  sent_at timestamp without time zone,
  CONSTRAINT rate_requests_pkey PRIMARY KEY (id),
  CONSTRAINT rate_requests_quotation_item_id_fkey FOREIGN KEY (quotation_item_id) REFERENCES public.quotation_items(id),
  CONSTRAINT rate_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT rate_requests_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id),
  CONSTRAINT rate_requests_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id)
);
CREATE TABLE public.sales_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid NOT NULL,
  product_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  discount_percent numeric DEFAULT 0,
  tax_percent numeric DEFAULT 0,
  line_total numeric NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sales_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT sales_order_items_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT sales_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.sales_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL UNIQUE,
  quotation_id uuid,
  customer_id uuid NOT NULL,
  business_entity_id uuid,
  order_date date NOT NULL,
  expected_delivery_date date,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'confirmed'::character varying::text, 'processing'::character varying::text, 'shipped'::character varying::text, 'delivered'::character varying::text, 'invoiced'::character varying::text, 'cancelled'::character varying::text])),
  subtotal numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  notes text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  delivery_date date,
  delivery_notes text,
  invoice_generated boolean DEFAULT false,
  CONSTRAINT sales_orders_pkey PRIMARY KEY (id),
  CONSTRAINT sales_orders_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id),
  CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT sales_orders_business_entity_id_fkey FOREIGN KEY (business_entity_id) REFERENCES public.business_entities(id),
  CONSTRAINT sales_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.shipment_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  product_id uuid,
  description text NOT NULL,
  hs_code_id uuid,
  quantity numeric NOT NULL,
  unit_price numeric,
  total_value numeric,
  currency character varying DEFAULT 'USD'::character varying,
  weight numeric,
  volume numeric,
  dimensions character varying,
  country_of_origin character varying,
  manufacturer character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT shipment_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_shipment_items_shipment FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT fk_shipment_items_hs_code FOREIGN KEY (hs_code_id) REFERENCES public.hs_codes(id)
);
CREATE TABLE public.shipments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_number character varying NOT NULL UNIQUE,
  shipment_type character varying NOT NULL CHECK (shipment_type::text = ANY (ARRAY['import'::character varying, 'export'::character varying]::text[])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_transit'::character varying, 'customs_clearance'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  purchase_order_id uuid,
  sales_order_id uuid,
  quotation_id uuid,
  customer_id uuid,
  vendor_id uuid,
  business_entity_id uuid,
  origin_port character varying,
  destination_port character varying,
  departure_date date,
  arrival_date date,
  estimated_arrival date,
  carrier_name character varying,
  vessel_name character varying,
  booking_reference character varying,
  container_number character varying,
  freight_cost numeric,
  freight_currency character varying DEFAULT 'USD'::character varying,
  shipping_terms character varying,
  incoterms character varying,
  gross_weight numeric,
  net_weight numeric,
  volume numeric,
  weight_unit character varying DEFAULT 'kg'::character varying,
  volume_unit character varying DEFAULT 'm3'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  notes text,
  tracking_number character varying,
  CONSTRAINT shipments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  movement_type character varying NOT NULL CHECK (movement_type::text = ANY (ARRAY['purchase'::character varying, 'sale'::character varying, 'adjustment'::character varying, 'transfer'::character varying, 'consumption'::character varying]::text[])),
  quantity numeric NOT NULL,
  unit_cost numeric,
  reference_type character varying,
  reference_id uuid,
  notes text,
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.system_settings (
  id integer NOT NULL DEFAULT nextval('system_settings_id_seq'::regclass),
  default_terms text,
  quotation_terms text,
  invoice_terms text,
  purchase_order_terms text,
  default_currency character varying DEFAULT 'USD'::character varying,
  default_tax_rate numeric DEFAULT 18.0,
  quotation_number_format character varying DEFAULT 'Q-YYYY-###'::character varying,
  invoice_number_format character varying DEFAULT 'INV-YYYY-###'::character varying,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trade_finance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  finance_type character varying NOT NULL,
  payment_terms character varying,
  payment_method character varying,
  credit_period integer,
  issuing_bank character varying,
  advising_bank character varying,
  confirming_bank character varying,
  required_documents ARRAY,
  total_amount numeric,
  currency character varying DEFAULT 'USD'::character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'issued'::character varying, 'confirmed'::character varying, 'utilized'::character varying, 'expired'::character varying, 'cancelled'::character varying]::text[])),
  issue_date date,
  expiry_date date,
  latest_shipment_date date,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  notes text,
  CONSTRAINT trade_finance_pkey PRIMARY KEY (id),
  CONSTRAINT fk_trade_finance_shipment FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['admin'::character varying, 'sales'::character varying, 'procurement'::character varying, 'finance'::character varying, 'auditor'::character varying]::text[])),
  is_active boolean DEFAULT true,
  last_login timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vendor_bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bill_number character varying NOT NULL,
  purchase_order_id uuid,
  vendor_id uuid NOT NULL,
  business_entity_id uuid,
  bill_date date NOT NULL,
  due_date date NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'paid'::character varying, 'overdue'::character varying]::text[])),
  subtotal numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  paid_amount numeric DEFAULT 0,
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT vendor_bills_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_bills_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT vendor_bills_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_bills_business_entity_id_fkey FOREIGN KEY (business_entity_id) REFERENCES public.business_entities(id),
  CONSTRAINT vendor_bills_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.vendor_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  category_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  assigned_by uuid,
  notes text,
  CONSTRAINT vendor_categories_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_categories_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id),
  CONSTRAINT vendor_categories_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  contact_person character varying,
  email character varying UNIQUE,
  phone character varying,
  tax_id character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  payment_terms integer DEFAULT 30,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  company_name character varying,
  credit_limit numeric DEFAULT 0,
  gst_number bigint,
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);